apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dnm4jp8qv-go 
  janus-idp.io/tekton: dnm4jp8qv-go
  backstage.io/kubernetes-id: dnm4jp8qv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dnm4jp8qv-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml