apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dnm4jp8qv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dnm4jp8qv-go 
  name: dnm4jp8qv-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dnm4jp8qv-go
    weight: 100 
